### ISSUE TITLE
How to eval/test ？

### ISSUE THREAD

**Issue by Lin-dashuai** [openmedlab/USFM#11]
That‘s a very very good sharing！

When i finished the training， how can i eval the model ？What command do I need to execute?

**Comment by George-Jiao** [comment]
Thanks for the suggestion. The newest version 2.0.0 of USFM has fixed the issue!

**Comment by JSerWP** [comment]
Thank you very much for your work!
 I would like to know what commands are needed to evaluate the model. I couldn't find the relevant information in the README.

**Comment by hu2274898** [comment]
Hi! Do you solve the problem?
