### ISSUE TITLE
Version Problem

### ISSUE THREAD

**Issue by dablro12** [openmedlab/USFM#13]
I have used ubuntu 20.04 LTS with CUDA 11.8 

but mmcv is not operated in my env(it can operate with cuda 12.2 and ubuntu 22.04) 

so Can you upload Dockerfile for using your model?

**Comment by George-Jiao** [comment]
Thanks for the suggestion. The newest version 2.0.0 of USFM has fixed the issue!

**Comment by dablro12** [comment]
Good...! I want to use it.
If I found other issue. I will suggest other issue for you :)
