### ISSUE TITLE
Issues concerning state_dict of the weights

### ISSUE THREAD

**Issue by George733** [openmedlab/USFM#15]
I'm curious why the state_dicts of the weights I trained from scratch using train.py differ from those of the downloaded weights( USFM_latest.pth & USFMpretrained.ckpt). 
Could you please guide me on how to set the YAML parameters so that I can effectively reuse the downloaded weights?

**Comment by George-Jiao** [comment]
We apologise for the cumbersome configuration of previous versions. You can try using the latest version 2.0.0
