### ISSUE TITLE
Request: Provide Pretrained Model via Hugging Face for Easier Integration

### ISSUE THREAD

**Issue by fadamsyah** [openmedlab/USFM#18]
Hi!

Thank you for your hard work on this project!

Would it be possible to provide the pretrained foundation model through Hugging Face's model hub? Integrating through Hugging Face would  simplify the dependency requirements, especially by removing the need for MM dependencies.

Thank you

**Comment by George-Jiao** [comment]
Thanks for the suggestion, we are planning to post USFM on hugging face.
