### ISSUE TITLE
The organ information for the two avaiable public datasets

### ISSUE THREAD

**Issue by Marxlp** [openmedlab/USFM#2]
I download the two dataset from google drive as described in the readme, the folder structure is show as below:

```shell
├── ImageSets
              ├── test.txt
              ├── train.txt
             └── val.txt
├── JPEGImages
              ├── 1.jpg
              ├── 10.jpg
               ....
└── SegmentationClass
               ├── 1.png
              ....
```

I want to get the organ info from the dataset, but after checking the file in `ImageSets`, `JPEGImages` and `SegmentationClass`, I found no such or related thing.

**Comment by George-Jiao** [comment]
Thanks for your interest in our project! The two datasets contain ultrasound images of the thyroid. There is no organ tag in the downstream datasets. In our paper, we have summarized a table to detail the organs of the datasets.
