### ISSUE TITLE
 I resolved an issue in your code“mmcv==2.2.0”

### ISSUE THREAD

**Issue by Licko0909** [openmedlab/USFM#21]
Thank you for your research contributions.  

During the process of running the demo, I resolved an issue in your code:  

I followed your instructions to set up the environment and prepare the toy data without encountering any errors. I successfully installed `mmcv==2.2.0`. However, when running fine-tuning on the toy segmentation data, an error occurred, indicating a version mismatch.  

To resolve the issue, I had to modify line 60 of `useful_modules/mmsegmentation/mmseg/__init__.py`, changing `"<2.2.0"` to `"<="2.2.0"`. This ultimately resolved the problem.

![75F332B9-EFA0-4470-9059-403E6B0C4B78](https://github.com/user-attachments/assets/397e14f9-a524-4990-9937-ca9f363fb543)

![A3B745C8-01CD-431D-BF7B-CB1F6DA7BC4C](https://github.com/user-attachments/assets/c9c62f03-9a71-4b48-b500-f39d0841d2b3)

![C3638584-1C9D-4B88-8D03-E1974D2A5911](https://github.com/user-attachments/assets/89331eed-0c92-472c-a47e-5b0349aa394f)

![image](https://github.com/user-attachments/assets/4afd339b-d3f0-4a0f-b948-c9dc3f56384e)

![image](https://github.com/user-attachments/assets/a10fb454-ad18-4018-b62e-b3353edc8c98)

**Comment by George-Jiao** [comment]
Thank you for your help. The solution for the issue "mmcv==2.2.0" has been implemented in the "_git@github.com:George-Jiao/mmsegmentation.git_ "and branch "_gj_mmcv2_2_0_". You can follow the guidelines to configure it:


```
mkdir -p useful_modules
cd useful_modules
git clone git@github.com:George-Jiao/mmsegmentation.git
cd mmsegmentation
git checkout gj_mmcv2_2_0
pip install -v -e .
cd ../..
```
