### ISSUE TITLE
MaskPre and MaskGT are all black

### ISSUE THREAD

**Issue by BodongDu** [openmedlab/USFM#22]
After I finish fit and test the USFM, I find the ouput images are all black in the log file?  What's wrong with them? 
![image](https://github.com/user-attachments/assets/dc732197-a140-4bb9-845e-72f607a3f5fb)

**Comment by BodongDu** [comment]
I followed all the instruction in your README file and using the best220.pth to test, the results are so bad!
![image](https://github.com/user-attachments/assets/59149705-b932-4d64-8eb2-dc3ade4616fb)

**Comment by BodongDu** [comment]
I have trained on eight 3090s for 4 hours and got such result?

**Comment by BodongDu** [comment]
def save_image(mask, path_dir, mask_path):
    file_name = os.path.join(path_dir, os.path.basename(mask_path))
    Image.fromarray(mask).save(file_name)


def save_seg_pre_gt(output_path, result, epoch, max_dice):
    # save the new checkpoint and folder
    mask_path_dir = os.path.join(output_path, f"best{epoch}_dice{max_dice:.3f}")

    mask_pre_path_dir = os.path.join(mask_path_dir, "mask_pre")
    mask_gt_path_dir = os.path.join(mask_path_dir, "mask_gt")
    os.makedirs(mask_path_dir, exist_ok=True)
    os.makedirs(mask_pre_path_dir, exist_ok=True)
    os.makedirs(mask_gt_path_dir, exist_ok=True)

    mask_pre_all = result["mask_pre_all"].numpy().astype(np.uint8)
    mask_path_all = result["mask_path_all"]
    mask_gt_all = result["mask_gt_all"].numpy().astype(np.uint8)
    for mask_gt, mask_pre, mask_path in zip(mask_gt_all, mask_pre_all, mask_path_all):
        save_image(mask_gt, mask_gt_path_dir, mask_path)
        save_image(mask_pre, mask_pre_path_dir, mask_path)

    return mask_path_dir

Are there any wrong with such visualize code? You know,  your Dice loss and IOU result is really cool!

**Comment by BodongDu** [comment]
Did you forget to scale to [0,255]?

**Comment by George-Jiao** [comment]
Thank you for pointing this out. Masks are stored as 0 and 1, like the original labels, or as 0, 1, 2, 3... for multi-object segmentation. You can scale the image yourself for visualization if needed.

**Comment by BodongDu** [comment]
I see, thanks for you reply!


Best regards,
Bodong Du



---Original---
From: ***@***.***&gt;
Date: Sun, Dec 1, 2024 21:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [openmedlab/USFM] MaskPre and MaskGT are all black (Issue #22)




 
Thank you for pointing this out. Masks are stored as 0 and 1, like the original labels, or as 0, 1, 2, 3... for multi-object segmentation. You can scale the image yourself for visualization if needed.
