### ISSUE TITLE
[Issue] [README]mmsegmentation 

### ISSUE THREAD

**Issue by dablro12** [openmedlab/USFM#23]
your README is incorrect this instruction 

(Before) git clone git@github.com:George-Jiao/mmsegmentation.git
(After) git clone https://github.com/George-Jiao/mmsegmentation.git

After this instruction. It's operating !!

And i used your Seg Datset(toy_dataset). but It cannot operating script 

below Error 
```

(USFM) eiden@eiden:~/[My dir]$ sh run_bash.sh 
In 'experiment/task/Seg': Could not find 'model/Seg/Segvit'

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/eiden/eiden/PCOS-roi-classification/reference/USFM/configs
        provider=hydra-colorlog, path=pkg://hydra_plugins.hydra_colorlog.conf
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

So how to solve this? Hydra Full Error

**Comment by George-Jiao** [comment]
The model name is Seg/SegVit

**Comment by dablro12** [comment]
![image](https://github.com/user-attachments/assets/6496d85d-c31f-4001-9462-8fb94bddac28)

Thank u! It's operated.
