### ISSUE TITLE
About 3M-US Databse 

### ISSUE THREAD

**Issue by Betty-J** [openmedlab/USFM#3]
Hi, thank you for sharing the work. May I ask if the 3M-US Database will be made public?

**Comment by jianghaojun** [comment]
+1

**Comment by George-Jiao** [comment]
Thanks for your interest. Most of the ultrasound images in the 3M-US database were obtained from the private databases of the collaborating hospitals. Its disclosure is prohibited by ethical safety. Our model will be continuously iterated and open-sourced.
