### ISSUE TITLE
The pre-training weight download failed

### ISSUE THREAD

**Issue by cyqyw1234** [openmedlab/USFM#4]
Hello, my Google Drive access is restricted and I can't download the weights of the pre-training. In addition, it is possible to provide classified training and validation instructions.

**Comment by George-Jiao** [comment]
Thank you for your interest. We have successfully tested the download of weights. You may need to make sure you have access to Google Drive. The implementation code for the downstream task will be updated soon.

**Comment by ccliyun** [comment]
![屏幕截图 2024-01-22 181113](https://github.com/openmedlab/USFM/assets/34147066/9500d579-c7b9-4932-af36-72f9a62eb107)
also failed

**Comment by ZiyangSong0230** [comment]
I also have the same problem.

**Comment by ZhangKe-Zoe** [comment]
same problem +1

**Comment by George-Jiao** [comment]
The download link: https://dl.orangedox.com/FDUUSFM. 
Can you test it again?

**Comment by ZhangKe-Zoe** [comment]
this link works，thx a lot!

> The download link: https://dl.orangedox.com/FDUUSFM. Can you test it again?
