### ISSUE TITLE
About finetuning USFM for classification and image enhanchment code

### ISSUE THREAD

**Issue by zhongniuniu** [openmedlab/USFM#6]
It's a good job. Can you publish the code for the classification and image enhancement experiments talked about in the article? So far I only see code about segmentation. Also from my observation, there are two modes of USFM used for downstream tasks, one is Adaptable pre-trained backbone and the other is Knowledgeable feature extractor. Which one is used in the current segmentation experiment? Can you please publish the other one as well? Thank you for your consideration of my question.

**Comment by George-Jiao** [comment]
Thanks for the suggestion. The newest version 2.0.0 of USFM has fixed the issue!
