### ISSUE TITLE
cannot download the weights

### ISSUE THREAD

**Issue by marcovisentin** [openmedlab/USFM#8]
Your weights should be at https://dl.orangedox.com/FDUUSFM but it returns "Page not found" and it seems that for the Google Drive link you shared https://drive.google.com/file/d/1_L_z34LOMxwhsqWpZwJ9eOPXvk_Wwd5N/view?usp=sharing permission is denied and needs to be requested (I did it). Any advice? Thank you!

**Comment by George-Jiao** [comment]
Thank you for raising this issue. The orangebox proxy support for our download links was expired. You can download the weight [USFM_lastet](https://drive.google.com/file/d/1NDbtB7U-emi4L8uiD47KKPtNApdaImTU/view?usp=drive_link) in google driver.

**Comment by marcovisentin** [comment]
Perfect, thank you!
